### PR TITLE
meta.yaml: add conda inspect lines

### PR DESCRIPTION
**Pull request by pkgw**
As suggested by @ocefpaf.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Here is the result:

```shell
+ conda inspect linkages -p /feedstock_root/build_artefacts/recipe_root_1484316166233/_t_env rpfits
rpfits
------

file:///feedstock_root/build_artefacts::rpfits-2.23-0:
    librpfits.so.0 (lib/librpfits.so.0)

libgfortran-3.0.0-1:
    libgfortran.so.3 (lib/libgfortran.so.3)

system:
    libc.so.6 (/lib64/libc.so.6)
    libgcc_s.so.1 (/lib64/libgcc_s.so.1)
    libm.so.6 (/lib64/libm.so.6)
    linux-vdso.so.1 ()

not found:


TEST END: rpfits-2.23-0
```

The first one (`build_artefacts`) is kind of weird but I guess it is harmless. And the fact that `not found` is empty is a good sign!

**Comment by jakirkham** [comment]
Unless I'm missing something special about this PR, please remember to fork the feedstock, create changes on your fork, and PR them back to the main feedstock. This is important as all branches on the main feedstock are configured to deploy as soon as they pass, which is not the case with one's fork.

**Comment by pkgw** [comment]
Ah, OK, didn't realize that all branches got run. Was hoping not to have to fork zillions of feedstock repositories to my personal account but so be it ...

**Comment by jakirkham** [comment]
> Ah, OK, didn't realize that all branches got run.

No worries. This is a common cause of confusion.

> Was hoping not to have to fork zillions of feedstock repositories to my personal account but so be it ...

Yeah, I understand it is not optimal in some ways. There was some discussion about restricting which branches deploy on a feedstock. Also to make management of this a little easier, I wrote a script to help one fork all feedstocks they maintain. If you know of other pain points that need to be solved, would be interested in discussing them with you.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/87
ref: https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/fork_my_feedstocks.py

**Pull request merged**
